source 'https://rubygems.org'

gem 'actionview'
gem 'activerecord'
gem 'config'
gem 'mini_magick'
gem 'octicons'
gem 'rake'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra'
gem 'sqlite3'
gem 'will_paginate'
gem 'streamio-ffmpeg'
